# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 04 May 2021 08:46:10 +0000
*               @ALL          0
*               @user         8
