<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Tue, 04 May 2021 08:46:10 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
